# Generated by Django 4.0.5 on 2022-07-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=250)),
                ('file_name', models.CharField(max_length=250)),
                ('image_folder', models.CharField(max_length=250)),
                ('contents', models.JSONField()),
            ],
        ),
    ]
