# Generated by Django 4.0.5 on 2022-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0003_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_uuid', models.CharField(max_length=36)),
                ('linked_uuid', models.CharField(max_length=36)),
                ('area_number', models.CharField(max_length=128)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('book_uuid', models.CharField(max_length=36)),
                ('page_number', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='questions_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('page_number', models.CharField(max_length=128)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='questions_sub_areas',
            fields=[
                ('sub_area_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('sub_area_number', models.CharField(max_length=128)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('book_uuid', models.CharField(max_length=36)),
                ('page_number', models.CharField(max_length=128)),
                ('main_uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('question_area_uuid', models.CharField(max_length=36)),
                ('datetime', models.DateTimeField(max_length=6)),
                ('result', models.CharField(max_length=32)),
                ('level', models.CharField(max_length=32)),
                ('book_uuid', models.CharField(max_length=36)),
            ],
        ),
    ]
