# Generated by Django 4.0.5 on 2022-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0004_questions_areas_questions_pages_questions_sub_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardapp_answers_areas',
            fields=[
                ('area_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('linked_uuid', models.CharField(max_length=36)),
                ('area_number', models.CharField(max_length=128)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('book_uuid', models.CharField(max_length=36)),
                ('page_number', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='cardapp_answers_book',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=2048)),
                ('image_folder', models.CharField(max_length=2048)),
                ('contents', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='cardapp_answers_pages',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('page_number', models.CharField(max_length=128)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cardapp_answers_sub_areas',
            fields=[
                ('sub_area_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('sub_area_number', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('book_uuid', models.CharField(max_length=36)),
                ('page_number', models.CharField(max_length=128)),
                ('main_uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='records',
            name='id',
        ),
        migrations.AlterField(
            model_name='records',
            name='count',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
